def raise_exception_msg(message="This is a custom type error."):